export const products = [
  {
    categoryId: 2,
    uomId: 4,
    code: 'WATER-500',
    nameEn: 'Bottled Water 500ml',
    nameKh: 'ទឹកសុទ្ធ ៥០០មល',
    description: 'Pure drinking water bottle 500ml',
    thumbnail: null,
    unitPrice: 0.5,
    createdById: 1,
  },
  {
    categoryId: 2,
    uomId: 4,
    code: 'COLA-330',
    nameEn: 'Cola Can 330ml',
    nameKh: 'កូឡាកំប៉ុង ៣៣០មល',
    description: 'Carbonated cola soft drink',
    thumbnail: null,
    unitPrice: 0.75,
    createdById: 1,
  },
  {
    categoryId: 1,
    uomId: 18,
    code: 'RICE-PLATE',
    nameEn: 'Rice Plate',
    nameKh: 'បាយមួយចាន',
    description: 'Steamed rice serving',
    thumbnail: null,
    unitPrice: 1.25,
    createdById: 1,
  },
  {
    categoryId: 3,
    uomId: 17,
    code: 'CHIPS-PAIR',
    nameEn: 'Potato Chips',
    nameKh: 'ដំឡូងបារាំងបំពង',
    description: 'Crispy potato snack',
    thumbnail: null,
    unitPrice: 1.1,
    createdById: 1,
  },
  {
    categoryId: 5,
    uomId: 18,
    code: 'BREAD-LOAF',
    nameEn: 'Bread Loaf',
    nameKh: 'នំបុ័ងដុំ',
    description: 'Fresh bakery bread loaf',
    thumbnail: null,
    unitPrice: 1.5,
    createdById: 1,
  },
  {
    categoryId: 4,
    uomId: 4,
    code: 'MILK-1L',
    nameEn: 'Fresh Milk 1L',
    nameKh: 'ទឹកដោះគោស្រស់ ១លីត្រ',
    description: 'Fresh dairy milk bottle',
    thumbnail: null,
    unitPrice: 2.25,
    createdById: 1,
  },
  {
    categoryId: 9,
    uomId: 4,
    code: 'SOAP-LIQ',
    nameEn: 'Liquid Soap',
    nameKh: 'សាប៊ូលាងដៃ',
    description: 'Hand washing liquid soap',
    thumbnail: null,
    unitPrice: 2.75,
    createdById: 1,
  },
  {
    categoryId: 8,
    uomId: 18,
    code: 'SHAMPOO-250',
    nameEn: 'Shampoo 250ml',
    nameKh: 'សាប៊ូកក់សក់ ២៥០មល',
    description: 'Personal care shampoo bottle',
    thumbnail: null,
    unitPrice: 3.5,
    createdById: 1,
  },
  {
    categoryId: 7,
    uomId: 23,
    code: 'TISSUE-ROLL',
    nameEn: 'Tissue Roll',
    nameKh: 'ក្រដាសជូតមាត់',
    description: 'Household tissue roll',
    thumbnail: null,
    unitPrice: 0.85,
    createdById: 1,
  },
  {
    categoryId: 6,
    uomId: 3,
    code: 'ICECREAM-BOX',
    nameEn: 'Ice Cream Box',
    nameKh: 'ការ៉េមប្រអប់',
    description: 'Frozen dessert box',
    thumbnail: null,
    unitPrice: 4.25,
    createdById: 1,
  },
];
