export const vendors = [
  {
    code: 'VND-001',
    nameEn: 'Fresh Market Supplier',
    nameKh: 'Fresh Market Supplier',
    phoneNumber: '+85512345678',
    email: 'fresh.market@example.com',
    address: 'Phnom Penh, Cambodia',
    profile: null,
    attachments: null,
    createdById: 1,
  },
  {
    code: 'VND-002',
    nameEn: 'Daily Goods Distribution',
    nameKh: 'Daily Goods Distribution',
    phoneNumber: '+85598765432',
    email: 'daily.goods@example.com',
    address: 'Siem Reap, Cambodia',
    profile: null,
    attachments: null,
    createdById: 1,
  },
  {
    code: 'VND-003',
    nameEn: 'Kitchen Supply Co.',
    nameKh: 'Kitchen Supply Co.',
    phoneNumber: '+85511223344',
    email: 'kitchen.supply@example.com',
    address: 'Battambang, Cambodia',
    profile: null,
    attachments: null,
    createdById: 1,
  },
];
